language: python
python:
  - "3.7"
install:
  - "pip install pytest"
script: python -m pytest tests/
deploy:
  provider: lambda
  function_name: "mytestlambda"
  region: "us-east-1"
  runtime: "python3.7"
  handler_name: "myfunction_handler"
  module_name: "mytestlambda"
  edge: true
  on:
    branch: master

